#ifndef DEFINE_H
#define DEFINE_H

#define HIGH_STRESS_COEFFICIENT 0.80
#define STRESS_FACTOR_COEFFICIENT 0.11
#define DEGREE_DIFFERENT_COEFFICIENT 0.0002
#define WEIGHT_PENALTY_COEFFICIENT 0.00015
#define SOFT_TIME_COEFFICIENT 0.995
#define MEDIUM_TIME_COEFFICIENT 1.00
#define HARD_TIME_COEFFICIENT 1.005
#define AVG_FUEL_COEFFICIENT 0.03
#define SOFT_TYRE_PENALTY 0.75
#define INVALID_LAP 999999.0
#define TOTAL_NUMBER_OF_TRACKS 24
#define PROBABILITY_CALCULATION_NUMBER 10000
#define MAX_STOP_NUMBER 7
#define SOFT_WINDOW_COEFFICIENT 0.1
#define MEDIUM_WINDOW_COEFFICIENT 0.2
#define HARD_WINDOW_COEFFICIENT 0.3

#endif